name = "neospacedecorweb"
compatibility_date = "2025-09-01"
main = "index.js"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "neospace-content"
database_id = "2077be47-8b31-4a0c-b8be-2b7531a04502"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "neospace-media"
